"""empty message

Revision ID: bae4ea73227a
Revises: 
Create Date: 2020-06-19 10:05:56.951548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae4ea73227a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('pose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('noisy_pose', sa.String(length=255), nullable=True),
    sa.Column('correct_pose', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pose_correct_pose'), 'pose', ['correct_pose'], unique=False)
    op.create_index(op.f('ix_pose_degree'), 'pose', ['degree'], unique=False)
    op.create_index(op.f('ix_pose_noisy_pose'), 'pose', ['noisy_pose'], unique=False)
    op.create_index(op.f('ix_pose_timestamp'), 'pose', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pose_timestamp'), table_name='pose')
    op.drop_index(op.f('ix_pose_noisy_pose'), table_name='pose')
    op.drop_index(op.f('ix_pose_degree'), table_name='pose')
    op.drop_index(op.f('ix_pose_correct_pose'), table_name='pose')
    op.drop_table('pose')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
